-- Migration: initial_schema
-- Project: LeanReserve
-- Generated by: Database Engineer Agent

BEGIN;

-- ── UPDATED_AT TRIGGER FUNCTION ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── TABLE: restaurants ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS restaurants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'Europe/Madrid',
  owner_id UUID REFERENCES auth.users(id), -- Linked to Supabase Auth
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_restaurants
  BEFORE UPDATE ON restaurants
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- ── TABLE: table_inventory ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS table_inventory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  capacity INT NOT NULL CHECK (capacity > 0),
  quantity INT NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_table_inventory
  BEFORE UPDATE ON table_inventory
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_table_inventory_restaurant_id ON table_inventory(restaurant_id);

-- ── TABLE: bookings ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TIME NOT NULL,
  guest_count INT NOT NULL CHECK (guest_count > 0),
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_bookings
  BEFORE UPDATE ON bookings
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- Performance Index for dashboard and availability checks
CREATE INDEX IF NOT EXISTS idx_bookings_date_restaurant ON bookings(booking_date, restaurant_id);

-- ── ROW LEVEL SECURITY (RLS) ────────────────────────────────────────────────

-- Enable RLS
ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE table_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Policies for: restaurants
CREATE POLICY "Owners can view/edit their own restaurant record" ON restaurants
  FOR ALL USING (auth.uid() = owner_id);

-- Policies for: table_inventory
CREATE POLICY "Owners can CRUD their own inventory" ON table_inventory
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM restaurants 
      WHERE restaurants.id = table_inventory.restaurant_id 
      AND restaurants.owner_id = auth.uid()
    )
  );

-- Policies for: bookings
CREATE POLICY "Owners can view/manage all bookings" ON bookings
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM restaurants 
      WHERE restaurants.id = bookings.restaurant_id 
      AND restaurants.owner_id = auth.uid()
    )
  );

CREATE POLICY "Public can only INSERT bookings" ON bookings
  FOR INSERT WITH CHECK (true);

COMMIT;